#ifndef GUARD_CONSTANTS_MAP_POPUP_THEMES_H
#define GUARD_CONSTANTS_MAP_POPUP_THEMES_H

// Vanilla Themes

#define MAPPOPUP_THEME_WOOD 0
#define MAPPOPUP_THEME_MARBLE 1
#define MAPPOPUP_THEME_STONE 2
#define MAPPOPUP_THEME_BRICK 3
#define MAPPOPUP_THEME_UNDERWATER 4
#define MAPPOPUP_THEME_STONE2 5

// BW Themes

#define MAPPOPUP_THEME_BW_DEFAULT 0

#endif  // GUARD_CONSTANTS_MAP_POPUP_THEMES_H
