gText_Birch_Welcome::
	.string "Hi! Sorry t me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "Welcome.\p"
	.string "My name is STEVEN.\p"
	.string "I used to be the POKéMON LEAGUE\n"
	.string "Champion from HOENN.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You may or may not know this,\n"
    .string "but all around the world there\l"
    .string "are many different POKéMON.\p"
    .string "Here in the SKÅNE region, new\n"
    .string "species have been found.\l"
    .string "Like this one.\p"
    .string "Some of them are related to\n"
    .string "POKéMON seen elsewhere.\p"
    .string "I came here to run the SKÅNE\n"
    .string "branch of the DEVON CORP. and\l"
    .string "help new trainers start their\l"
    .string "new and wonderful journey.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you male?\n"
	.string "Or are you female?$"

gText_Birch_WhatsYourName::
	.string "All right then.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Well done!\p"
	.string "You're {PLAYER}{KUN} who just moved\n"
	.string "to the SKÅNE Region.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right.\p"
    .string "You've been a powerful trainer\n"
    .string "at the BATTLE FRONTIER.\l"
    .string "Now it's time for a new challenge\l"
    .string "with new people and new POKéMON.\p"
    .string "Come meet me in TWO CITY and\n" @ x_MODIFY_x
    .string "I'll get you started.\p"
	.string "$"
